# Generated by Django 4.2.11 on 2024-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
