# Generated by Django 4.2.11 on 2024-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
