# Generated by Django 5.1.1 on 2024-11-20 10:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_customuser_paypay_id_project_total_investment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="point_adjustment",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=10
            ),
        ),
    ]
