# Generated by Django 5.1.1 on 2024-11-27 10:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_milestone_base_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="milestone",
            name="base_points",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="num_children",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="point_adjustment",
        ),
        migrations.AddField(
            model_name="milestone",
            name="auto_points",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="manual_points",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="points",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
